// -----------------------------------------------------------------------
// <copyright file="KindOfType.cs" company="NewSage">
// A transliteration and update of the CnC Generals (Zero Hour) engine and games with mod-first support.
// Copyright (C) 2025 NewSage Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see https://www.gnu.org/licenses/.
// </copyright>
// -----------------------------------------------------------------------

namespace NewSage.Game.Masks;

[BitMasks]
internal enum KindOfType
{
    Invalid = -1,
    Obstacle,
    Selectable,
    Immobile,
    CanAttack,
    StickToTerrainSlope,
    CanCastReflections,
    Shrubbery,
    Structure,
    Infantry,
    Vehicle,
    Aircraft,
    HugeVehicle,
    Dozer,
    Harvester,
    CommandCenter,
    Prison,
    CollectsPrisonBounty,
    PowTruck,
    LineBuild,
    Salvager,
    WeaponSalvager,
    Transport,
    Bridge,
    LandmarkBridge,
    BridgeTower,
    Projectile,
    Preload,
    NoGarrison,
    WaveGuid,
    WaveEffect,
    NoCollide,
    RepairPad,
    HealPad,
    StealthGarrison,
    CashGenerator,
    DrawableOnly,
    MultiPlayerCountForVictory,
    RebuildHole,
    Score,
    ScoreCreate,
    ScoreDestroy,
    NoHealIcon,
    CanRappel,
    Parachutable,
    CanSurrender,
    CanBeRepulsed,
    MobNexus,
    IgnoredInGui,
    Crate,
    Capturable,
    ClearedByBuild,
    SmallMissile,
    AlwaysVisible,
    Unattackable,
    Mine,
    CleanupHazard,
    PortableStructure,
    AlwaysSelectable,
    AttackNeedsLineOfSight,
    WalkOnTopOfWall,
    DefensiveWall,
    FactionStructurePower,
    FactionStructureFactory,
    FactionStructureBaseDefense,
    FactionStructureTechnology,
    AircraftPathAround,
    LowOverlappable,
    ForceAttackable,
    AutoRallyPoint,
    TechBuilding,
    Powered,
    ProducedAtHelipad,
    Drone,
    CanSeeThroughStructure,
    BallisticMissile,
    ClickThrough,
    SupplySourceOnPreview,
    Parachute,
    GarrisonableUntilDestroyed,
    Boat,
    ImmuneToCapture,
    Hulk,
    ShowPortraitWhenControlled,
    SpawnsAreTheWeapons,
    CannotBuildNearSupplies,
    SupplySource,
    RevealToAll,
    Disguiser,
    Inert,
    Hero,
    IgnoresSelectAll,
    DontAutoCrushInfantry,
    CliffJumper,
    FactionStructureSupplyDropZone,
    FactionStructureSuperWeapon,
    FactionStructureBlackMarket,
    FactionStructureSupplyCenter,
    FactionStructureStrategyCenter,
    MoneyHacker,
    ArmorSalvager,
    RevealsEnemyPaths,
    BoobyTrap,
    FactionStructureFake,
    FactionStructureInternetCenter,
    BlastCrater,
    Prop,
    OptimizedTree,
    FactionStructureAdvancedTech,
    FactionStructureBarracks,
    FunctionStructureWarFactory,
    FunctionStructureAirfield,
    AircraftCarrier,
    NoSelect,
    RejectUnmanned,
    CannotRetaliate,
    TechBaseDefense,
    EmpHardened,
    DemoTrap,
    ConservativeBuilding,
    IgnoreDockingBones,
}
